package garage.assistant.ui.main;

import com.jfoenix.effects.JFXDepthManager;
import garage.assistant.database.DatabaseHandler;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

public class MainController implements Initializable {

    @FXML
    private HBox motorbike_info;
    @FXML
    private HBox member_info;
    @FXML
    private TextField motorbikeIdInput;
    @FXML
    private Text motorbikeProducer;
    @FXML
    private Text motorbikeID;
    @FXML
    private Text motorbikeName;
    @FXML
    private Text motorbikeStatus;
    
    DatabaseHandler dbHandler;

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        
        //[UI] set depth
        JFXDepthManager.setDepth(motorbike_info, 1); //0 - 5
        JFXDepthManager.setDepth(member_info, 1);
        
        dbHandler = DatabaseHandler.getInstance();
    }    

    @FXML
    private void loadAddMember(ActionEvent event) {
        loadWindow("/garage/assistant/ui/addmember/member_add.fxml",
                "/garage/assistant/viewable/member.png", "Add new Member");
    }

    @FXML
    private void loadAddMotorbike(ActionEvent event) {
        loadWindow("/garage/assistant/ui/addmotorbike/add_motorbike.fxml",
                "/garage/assistant/viewable/mobtorbike.png", "Add new Motorbike");
    }

    @FXML
    private void loadMemberTable(ActionEvent event) {
        loadWindow("/garage/assistant/ui/listmember/member_list.fxml",
                "/garage/assistant/viewable/member_list.png","All Member");
    }

    @FXML
    private void loadMotorbikeTable(ActionEvent event) {
        loadWindow("/garage/assistant/ui/listmotorbike/motorbike_list.fxml",
                "/garage/assistant/viewable/motorbile_list.png","All Motorbike");
    }
    
    //call another window in-app
    void loadWindow(String dirLct, String dirIcon, String title) {
        try {
            Parent parent  = FXMLLoader.load(getClass().getResource(dirLct));
            Stage stage = new Stage(StageStyle.DECORATED);
            stage.setTitle(title);
            stage.setScene(new Scene(parent));
            
            //set icon
            Image ico = new Image(dirIcon);
            stage.getIcons().add(ico);
            
            stage.show();
            
        } catch (IOException ex) { //auto generated by try-catch
            Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @FXML
    private void loadMotorbikeInfo(ActionEvent event) {
        String id = motorbikeIdInput.getText();
        String qr = "SELECT * FROM MOTORBIKE WHERE idMotorbike = '" + id + "'";
        
        ResultSet rs = dbHandler.excQuery(qr);
        
        Boolean flag = false;
        
        try {
            while(rs.next()) {
                String mbProducer = rs.getString("producer");
                String mbID = rs.getString("idMotorbike");
                String mbName = rs.getString("name");
                Boolean mbStatus = rs.getBoolean("isAvail");
                
                motorbikeProducer.setText(mbProducer);
                motorbikeID.setText(mbID);
                motorbikeName.setText(mbName);
                
                String stt = (mbStatus)?"Available" : "NOT Available";
                motorbikeStatus.setText(stt);
                flag = true;
            }
            if( !flag ) {
                motorbikeName.setText("Can find the Motorbike");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}